"""added path and index

Revision ID: a6a0146e3ca3
Revises: 
Create Date: 2024-06-05 19:17:21.383409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a0146e3ca3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=128), nullable=False),
    sa.Column('file_content', sa.Text(), nullable=False),
    sa.Column('file_type', sa.String(length=128), nullable=False),
    sa.Column('file_size', sa.String(length=30), nullable=False),
    sa.Column('file_abs_path', sa.String(length=256), nullable=False),
    sa.Column('file_rel_path', sa.String(length=256), nullable=False),
    sa.Column('date_modified', sa.String(length=140), nullable=False),
    sa.Column('tags', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name'),
    sa.UniqueConstraint('file_name', 'file_type', name='uix_file_name_file_type')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_file_size'), ['file_size'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_file_type'), ['file_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_file_type'))
        batch_op.drop_index(batch_op.f('ix_document_file_size'))

    op.drop_table('document')
    # ### end Alembic commands ###
