"""changed size to not unqiue

Revision ID: ecb087627ec1
Revises: 
Create Date: 2024-06-04 21:30:05.230635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb087627ec1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index('ix_document_file_size')

    op.drop_table('document')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=128), nullable=False),
    sa.Column('file_content', sa.TEXT(), nullable=False),
    sa.Column('file_classification', sa.VARCHAR(length=128), nullable=False),
    sa.Column('file_size', sa.VARCHAR(length=120), nullable=True),
    sa.Column('tags', sa.VARCHAR(length=256), nullable=True),
    sa.Column('date_modified', sa.VARCHAR(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_name')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index('ix_document_file_size', ['file_size'], unique=1)

    # ### end Alembic commands ###
