"""added abs_path update

Revision ID: 7ac3c6306310
Revises: 3a3224673545
Create Date: 2024-06-05 20:23:59.742397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac3c6306310'
down_revision = '3a3224673545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint('uix_name_type', type_='unique')
        batch_op.create_unique_constraint('uix_name_type_abs_path', ['name', 'type', 'abs_path'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint('uix_name_type_abs_path', type_='unique')
        batch_op.create_unique_constraint('uix_name_type', ['name', 'type'])

    # ### end Alembic commands ###
