"""removed content

Revision ID: caa7fedc9ab6
Revises: 7ac3c6306310
Create Date: 2024-06-06 18:54:34.677602

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "caa7fedc9ab6"
down_revision = "7ac3c6306310"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.create_unique_constraint("uix_abs_path", ["abs_path"])
        batch_op.drop_column("content")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document", schema=None) as batch_op:
        batch_op.add_column(sa.Column("content", sa.TEXT(), nullable=False))
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
